// Generated by scripts/vite-plugin-blog.js from src/content/blog. Do not edit by hand.
export const BLOG_SLUGS = [
  "how-my-pm-job-changed-in-a-year",
  "why-hobbies-matter-in-corporate-life",
  "the-gold-in-rejected-calls",
  "from-darjeeling-to-iit-dhanbad"
];
